export const packetNames = [
  'C2SRegister',
  'S2CRegister',
  'C2SLogin',
  'S2CLogin',
  'C2SCreateCharacter',
  'S2CCreateCharacter',
  'C2STownEnter',
  'S2CTownEnter',
  'C2STownLeave',
  'S2CTownLeave',
  'C2SAnimation',
  'S2CAnimation',
  'C2SChat',
  'S2CChat',
  'S2CPlayerSpawn',
  'S2CPlayerDespawn',
  'C2SPlayerMove',
  'S2CPlayerMove',
  'C2SPlayerLocation',
  'S2CPlayerLocation',
  'C2SPlayerCollision',
  'S2CPlayerCollision',
  'C2SMonsterCollision',
  'S2CMonsterCollision',
  'C2SCreateParty',
  'S2CCreateParty',
  'C2SInviteParty',
  'S2CInviteParty',
  'C2SJoinParty',
  'S2CJoinParty',
  'C2SLeaveParty',
  'S2CLeaveParty',
  'C2SSetPartyLeader',
  'S2CSetPartyLeader',
  'C2SKickOutMember',
  'S2CKickOutMember',
  'C2SDisbandParty',
  'C2SAllowInvite',
  'S2CAllowInvite',
  'S2CDisbandParty',
  'C2SSectorEnter',
  'S2CSectorEnter',
  'C2SSectorLeave',
  'S2CSectorLeave',
  'C2SInPortal',
  'S2CInPortal',
  'C2SAttack',
  'S2CAttack',
  'C2SHit',
  'S2CHit',
  'S2CDie',
  'C2SMonsterLocation',
  'S2CMonsterLocation',
];

/* 기존 코드 */
// export const packetNames = [
//   'C_Enter',
//   'S_Enter',
//   'S_Spawn',
//   'S_Despawn',
//   'C_Location',
//   'S_Location',
//   'C_Move',
//   'S_Move',
//   'C_Animation',
//   'S_Animation',
//   'S_Chat',
//   'C_Chat',
//   'C_EnterDungeon',
//   'C_PlayerResponse',
//   'S_EnterDungeon',
//   'S_LeaveDungeon',
//   'S_ScreenText',
//   'S_ScreenDone',
//   'S_BattleLog',
//   'S_SetPlayerHp',
//   'S_SetPlayerMp',
//   'S_SetMonsterHp',
//   'S_PlayerAction',
//   'S_MonsterAction',
//   'C_Register',
//   'S_Register',
//   'C_Login',
//   'S_Login',
//   'C_CreateCharacter',
//   'S_CreateCharacter'
// ];
