import {
  PORT,
  HOST,
  CLIENT_VERSION,
  DB1_NAME,
  DB1_USER,
  DB1_PASSWORD,
  DB1_HOST,
  DB1_PORT,
} from '../constants/env.js';
import {
  PACKET_ID,
  PACKET_ID_LENGTH,
  PACKET_SIZE,
} from '../constants/header.js';
import { BASE_STAT_DATA } from '../constants/PlayerBaseStat.js';
import { BATTLE_LOG_ID } from '../constants/BattleLog.js';
import { UPDATE_LOCATION } from '../constants/UpdateLocation.js';
export const config = {
  server: {
    port: PORT,
    host: HOST,
  },
  client: {
    version: CLIENT_VERSION,
  },
  packet: {
    totalSize: PACKET_SIZE,
    idLength: PACKET_ID_LENGTH,
  },
  databases: {
    PROJECT_R_USER_DB: {
      name: DB1_NAME,
      user: DB1_USER,
      password: DB1_PASSWORD,
      host: DB1_HOST,
      port: DB1_PORT,
    },
  },
  packetId: {
    C2SRegister: PACKET_ID.C2SRegister,
    S2CRegister: PACKET_ID.S2CRegister,
    C2SLogin: PACKET_ID.C2SLogin,
    S2CLogin: PACKET_ID.S2CLogin,
    C2SCreateCharacter: PACKET_ID.C2SCreateCharacter,
    S2CCreateCharacter: PACKET_ID.S2CCreateCharacter,
    C2STownEnter: PACKET_ID.C2STownEnter,
    S2CTownEnter: PACKET_ID.S2CTownEnter,
    C2STownLeave: PACKET_ID.C2STownLeave,
    S2CTownLeave: PACKET_ID.S2CTownLeave,
    C2SAnimation: PACKET_ID.C2SAnimation,
    S2CAnimation: PACKET_ID.S2CAnimation,
    C2SChat: PACKET_ID.C2SChat,
    S2CChat: PACKET_ID.S2CChat,
    S2CPlayerSpawn: PACKET_ID.S2CPlayerSpawn,
    S2CPlayerDespawn: PACKET_ID.S2CPlayerDespawn,
    C2SPlayerMove: PACKET_ID.C2SPlayerMove,
    S2CPlayerMove: PACKET_ID.S2CPlayerMove,
    C2SPlayerLocation: PACKET_ID.C2SPlayerLocation,
    S2CPlayerLocation: PACKET_ID.S2CPlayerLocation,
    C2SPlayerCollision: PACKET_ID.C2SPlayerCollision,
    S2CPlayerCollision: PACKET_ID.S2CPlayerCollision,
    C2SMonsterCollision: PACKET_ID.C2SMonsterCollision,
    S2CMonsterCollision: PACKET_ID.S2CMonsterCollision,
    C2SCreateParty: PACKET_ID.C2SCreateParty,
    S2CCreateParty: PACKET_ID.S2CCreateParty,
    C2SInviteParty: PACKET_ID.C2SInviteParty,
    S2CInviteParty: PACKET_ID.S2CInviteParty,
    C2SJoinParty: PACKET_ID.C2SJoinParty,
    S2CJoinParty: PACKET_ID.S2CJoinParty,
    C2SLeaveParty: PACKET_ID.C2SLeaveParty,
    S2CLeaveParty: PACKET_ID.S2CLeaveParty,
    C2SSetPartyLeader: PACKET_ID.C2SSetPartyLeader,
    S2CSetPartyLeader: PACKET_ID.S2CSetPartyLeader,
    C2SBuff: PACKET_ID.C2SBuff,
    S2CBuff: PACKET_ID.S2CBuff,
    C2SDungeonEnter: PACKET_ID.C2SDungeonEnter,
    S2CDungeonEnter: PACKET_ID.S2CDungeonEnter,
    C2SDungeonLeave: PACKET_ID.C2SDungeonLeave,
    S2CDungeonLeave: PACKET_ID.S2CDungeonLeave,
    C2SAttack: PACKET_ID.C2SAttack,
    S2CAttack: PACKET_ID.S2CAttack,
    C2SHit: PACKET_ID.C2SHit,
    S2CHit: PACKET_ID.S2CHit,
    S2CDie: PACKET_ID.S2CDie,
    C2SMonsterLocation: PACKET_ID.C2SMonsterLocation,
    S2CMonsterLocation: PACKET_ID.S2CMonsterLocation,
    //#region /* 채집관련 */
    S2CResourcesList: PACKET_ID.S2CResourcesList,
    S2CUpdateDurability: PACKET_ID.S2CUpdateDurability,
    C2SStartGathering: PACKET_ID.C2SStartGathering,
    S2CStartGathering: PACKET_ID.S2CStartGathering,
    C2SGatheringSkillCheck: PACKET_ID.C2SGatheringSkillCheck,
    S2CGatheringSkillCheck: PACKET_ID.S2CGatheringSkillCheck,
    S2CGatheringDone: PACKET_ID.S2CGatheringDone,
    //#endregion
    /* 기존 코드 */
    // C_Enter: PACKET_ID.C_Enter,
    // S_Enter: PACKET_ID.S_Enter,
    // S_Spawn: PACKET_ID.S_Spawn,
    // S_Despawn: PACKET_ID.S_Despawn,
    // C_Location: PACKET_ID.C_Location,
    // S_Location: PACKET_ID.S_Location,
    // C_Move: PACKET_ID.C_Move,
    // S_Move: PACKET_ID.S_Move,
    // C_Animation: PACKET_ID.C_Animation,
    // S_Animation: PACKET_ID.S_Animation,
    // C_Chat: PACKET_ID.C_Chat,
    // S_Chat: PACKET_ID.S_Chat,
    // C_EnterDungeon: PACKET_ID.C_EnterDungeon,
    // C_PlayerResponse: PACKET_ID.C_PlayerResponse,
    // S_EnterDungeon: PACKET_ID.S_EnterDungeon,
    // S_LeaveDungeon: PACKET_ID.S_LeaveDungeon,
    // S_ScreenText: PACKET_ID.S_ScreenText,
    // S_ScreenDone: PACKET_ID.S_ScreenDone,
    // S_BattleLog: PACKET_ID.S_BattleLog,
    // S_SetPlayerHp: PACKET_ID.S_SetPlayerHp,
    // S_SetPlayerMp: PACKET_ID.S_SetPlayerMp,
    // S_SetMonsterHp: PACKET_ID.S_SetMonsterHp,
    // S_PlayerAction: PACKET_ID.S_PlayerAction,
    // S_MonsterAction: PACKET_ID.S_MonsterAction,
    // C_Register: PACKET_ID.C_Register,
    // S_Register: PACKET_ID.S_Register,
    // C_Login: PACKET_ID.C_Login,
    // S_Login: PACKET_ID.S_Login,
    // C_CreateCharacter : PACKET_ID.C_CreateCharacter,
    // S_CreateCharacter : PACKET_ID.S_CreateCharacter
  },
  newPlayerStatData: {
    BASE_STAT_DATA,
  },
  battletag: {
    Menu: BATTLE_LOG_ID.menu,
    Attack: BATTLE_LOG_ID.attack,
  },
  updateLocation: {
    tolerance: UPDATE_LOCATION.tolerance,
  },
};

export const packetIdEntries = Object.entries(config.packetId);
